README.org ---  description



Copyright (C) 2005-2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>

  

  This file is part of port-expander.
  
  port-expander is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  port-expander is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with port-expander.  If not, see <http://www.gnu.org/licenses/>.
  
  
  
* Keywords:
  i2c port bus expander 8-bit
  

* Description:
  
  
  
* Usage:
  
  read with emacs (3__3) org mode
  
  
  
  
* History:

  initial project version began about 2013.05(May).21 

  
  
  
* Dependences:
  
  

* Code:


